QBShared = QBShared or {}
QBShared.Items = {

  -- Restaurant Items
    ["restaurant_food"] = { name = "restaurant_food", label = "Restaurant food", weight = 0, type = "item", image = "", unique = true, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["restaurant_box"] = { name = "restaurant_box", label = "Restaurant box", weight = 0, type = "item", image = "restaurant_box.png", unique = true, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Raw Ingredients
    ["onion"] = { name = "onion", label = "Onion", weight = 8, type = "item", image = "onion.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["carrot"] = { name = "carrot", label = "Carrot", weight = 8, type = "item", image = "carrot.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["lettuce"] = { name = "lettuce", label = "Lettuce", weight = 8, type = "item", image = "lettuce.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cucumber"] = { name = "cucumber", label = "Cucumber", weight = 8, type = "item", image = "cucumber.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["potato"] = { name = "potato", label = "Potato", weight = 8, type = "item", image = "potato.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tomato"] = { name = "tomato", label = "Tomato", weight = 8, type = "item", image = "tomato.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["coffee_beans"] = { name = "coffee_beans", label = "Coffee Beans", weight = 8, type = "item", image = "coffee_beans.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["wheat"] = { name = "wheat", label = "Wheat", weight = 8, type = "item", image = "wheat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["corn"] = { name = "corn", label = "Corn", weight = 8, type = "item", image = "corn.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Fruits
    ["strawberry"] = { name = "strawberry", label = "Strawberry", weight = 8, type = "item", image = "strawberry.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["watermelon"] = { name = "watermelon", label = "Watermelon", weight = 8, type = "item", image = "watermelon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["soya"] = { name = "soya", label = "Soya", weight = 8, type = "item", image = "soya.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pineapple"] = { name = "pineapple", label = "Pineapple", weight = 8, type = "item", image = "pineapple.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["apple"] = { name = "apple", label = "Apple", weight = 8, type = "item", image = "apple.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pear"] = { name = "pear", label = "Pear", weight = 8, type = "item", image = "pear.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["lemon"] = { name = "lemon", label = "Lemon", weight = 8, type = "item", image = "lemon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["banana"] = { name = "banana", label = "Banana", weight = 8, type = "item", image = "banana.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["orange"] = { name = "orange", label = "Orange", weight = 8, type = "item", image = "orange.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["peach"] = { name = "peach", label = "Peach", weight = 8, type = "item", image = "peach.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["mango"] = { name = "mango", label = "Mango", weight = 8, type = "item", image = "mango.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["blueberries"] = { name = "blueberries", label = "Blueberries", weight = 8, type = "item", image = "blueberries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Meat and Fish
    ["meat"] = { name = "meat", label = "Meat", weight = 8, type = "item", image = "meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["fish"] = { name = "fish", label = "Fish", weight = 8, type = "item", image = "fish.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["raw_meat"] = { name = "raw_meat", label = "Raw Meat", weight = 8, type = "item", image = "raw_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["squid"] = { name = "squid", label = "Squid", weight = 8, type = "item", image = "squid.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Cut Ingredients
    ["cutted_meat"] = { name = "cutted_meat", label = "Cutted Meat", weight = 8, type = "item", image = "cutted_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_fish"] = { name = "cutted_fish", label = "Cutted Fish", weight = 8, type = "item", image = "cutted_fish.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_onion"] = { name = "cutted_onion", label = "Cutted Onion", weight = 8, type = "item", image = "cutted_onion.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_carrot"] = { name = "cutted_carrot", label = "Cutted Carrot", weight = 8, type = "item", image = "cutted_carrot.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_lettuce"] = { name = "cutted_lettuce", label = "Cutted Lettuce", weight = 8, type = "item", image = "cutted_lettuce.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_cucumber"] = { name = "cutted_cucumber", label = "Cutted Cucumber", weight = 8, type = "item", image = "cutted_cucumber.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_potato"] = { name = "cutted_potato", label = "Cutted Potato", weight = 8, type = "item", image = "cutted_potato.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_tomato"] = { name = "cutted_tomato", label = "Cutted Tomato", weight = 8, type = "item", image = "cutted_tomato.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_wheat"] = { name = "cutted_wheat", label = "Flour", weight = 8, type = "item", image = "cutted_wheat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_strawberry"] = { name = "cutted_strawberry", label = "Cutted Strawberry", weight = 8, type = "item", image = "cutted_strawberry.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_watermelon"] = { name = "cutted_watermelon", label = "Cutted Watermelon", weight = 8, type = "item", image = "cutted_watermelon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_soya"] = { name = "cutted_soya", label = "Tofu", weight = 8, type = "item", image = "cutted_soya.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_pineapple"] = { name = "cutted_pineapple", label = "Cutted Pineapple", weight = 8, type = "item", image = "cutted_pineapple.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_apple"] = { name = "cutted_apple", label = "Cutted Apple", weight = 8, type = "item", image = "cutted_apple.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_pear"] = { name = "cutted_pear", label = "Cutted Pear", weight = 8, type = "item", image = "cutted_pear.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_lemon"] = { name = "cutted_lemon", label = "Cutted Lemon", weight = 8, type = "item", image = "cutted_lemon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_banana"] = { name = "cutted_banana", label = "Cutted Banana", weight = 8, type = "item", image = "cutted_banana.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_peach"] = { name = "cutted_peach", label = "Cutted Peach", weight = 8, type = "item", image = "cutted_peach.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_mango"] = { name = "cutted_mango", label = "Cutted Mango", weight = 8, type = "item", image = "cutted_mango.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cutted_orange"] = { name = "cutted_orange", label = "Cutted Orange", weight = 8, type = "item", image = "cutted_orange.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Backwoods
    ["backwoods_honey"] = { name = "backwoods_honey", label = "Backwoods Honey", weight = 8, type = "item", image = "backwoods_honey.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["backwoods_russian_cream"] = { name = "backwoods_russian_cream", label = "Backwoods Russian Cream", weight = 8, type = "item", image = "backwoods_russian_cream.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Prepared Foods
    ["bacon_cheese_fries"] = { name = "bacon_cheese_fries", label = "Bacon Cheese Fries", weight = 8, type = "item", image = "bacon_cheese_fries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bacon_eggs"] = { name = "bacon_eggs", label = "Bacon & Eggs", weight = 8, type = "item", image = "bacon_eggs.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["basket_fries"] = { name = "basket_fries", label = "Basket Fries", weight = 8, type = "item", image = "basket_fries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bbq_ribs"] = { name = "bbq_ribs", label = "BBQ Ribs", weight = 8, type = "item", image = "bbq-ribs.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["blueberry_pie"] = { name = "blueberry_pie", label = "Blueberry Pie", weight = 8, type = "item", image = "blueberry_pie.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["boiled_meat"] = { name = "boiled_meat", label = "Boiled Meat", weight = 8, type = "item", image = "boiled_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burned_meat"] = { name = "burned_meat", label = "Burned Meat", weight = 8, type = "item", image = "burned_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Canned Foods
    ["canned_chicken_soup"] = { name = "canned_chicken_soup", label = "Canned Chicken Soup", weight = 8, type = "item", image = "canned_chicken_soup.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["canned_country_soup"] = { name = "canned_country_soup", label = "Canned Country Soup", weight = 8, type = "item", image = "canned_country_soup.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["canned_pears"] = { name = "canned_pears", label = "Canned Pears", weight = 8, type = "item", image = "canned_pears.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["canned_peas"] = { name = "canned_peas", label = "Canned Peas", weight = 8, type = "item", image = "canned_peas.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["canned_salmon"] = { name = "canned_salmon", label = "Canned Salmon", weight = 8, type = "item", image = "canned_salmon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["canned_tuna"] = { name = "canned_tuna", label = "Canned Tuna", weight = 8, type = "item", image = "canned_tuna.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- More Prepared Foods
    ["cheese_fries"] = { name = "cheese_fries", label = "Cheese Fries", weight = 8, type = "item", image = "cheese_fries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chicken_caesar_wrap"] = { name = "chicken_caesar_wrap", label = "Chicken Caesar Wrap", weight = 8, type = "item", image = "chicken_caesar_wrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chicken_strips"] = { name = "chicken_strips", label = "Chicken Strips", weight = 8, type = "item", image = "chicken_strips.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chicken_sstrip2"] = { name = "chicken_sstrip2", label = "Chicken Strip 2", weight = 8, type = "item", image = "chicken_sstrip2.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chilli_bowl"] = { name = "chilli_bowl", label = "Chilli Bowl", weight = 8, type = "item", image = "chilli_bowl.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chilli_dog"] = { name = "chilli_dog", label = "Chilli Dog", weight = 8, type = "item", image = "chilli_dog.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cooked_fish"] = { name = "cooked_fish", label = "Cooked Fish", weight = 8, type = "item", image = "cooked_fish.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["corn_bread"] = { name = "corn_bread", label = "Corn Bread", weight = 8, type = "item", image = "corn_bread.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["corn_crop"] = { name = "corn_crop", label = "Corn Crop", weight = 8, type = "item", image = "corn_crop.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["corn_meal"] = { name = "corn_meal", label = "Corn Meal", weight = 8, type = "item", image = "corn_meal.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["corn_on_cob"] = { name = "corn_on_cob", label = "Corn on Cob", weight = 8, type = "item", image = "corn_on_cob.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["covert_cat"] = { name = "covert_cat", label = "Covert Cat", weight = 8, type = "item", image = "covert_cat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Eggs
    ["egg_boiled"] = { name = "egg_boiled", label = "Egg Boiled", weight = 8, type = "item", image = "egg_boiled.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["egg_raw"] = { name = "egg_raw", label = "Egg Raw", weight = 8, type = "item", image = "egg_raw.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- More Food Items
    ["eye_kandy"] = { name = "eye_kandy", label = "Eye Kandy", weight = 8, type = "item", image = "eye_kandy.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["fish_taco"] = { name = "fish_taco", label = "Fish Taco", weight = 8, type = "item", image = "fish_taco.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["foodBaconAndEggs"] = { name = "foodBaconAndEggs", label = "Bacon and Eggs", weight = 8, type = "item", image = "foodBaconAndEggs.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["foodBlueberryPie"] = { name = "foodBlueberryPie", label = "Blueberry Pie", weight = 8, type = "item", image = "foodBlueberryPie.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["foodEggBoiled"] = { name = "foodEggBoiled", label = "Egg Boiled", weight = 8, type = "item", image = "foodEggBoiled.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["foodGrilledMeat"] = { name = "foodGrilledMeat", label = "Grilled Meat", weight = 8, type = "item", image = "foodGrilledMeat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["fruit_box"] = { name = "fruit_box", label = "Fruit Box", weight = 8, type = "item", image = "fruit-box.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["grain_oatmeal"] = { name = "grain_oatmeal", label = "Grain Oatmeal", weight = 8, type = "item", image = "grain_oatmeal.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["greek_veggie_wrap"] = { name = "greek_veggie_wrap", label = "Greek Veggie Wrap", weight = 8, type = "item", image = "greek_veggie_wrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["grilled_meat"] = { name = "grilled_meat", label = "Grilled Meat", weight = 8, type = "item", image = "grilled_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["gumbo_stew"] = { name = "gumbo_stew", label = "Gumbo Stew", weight = 8, type = "item", image = "gumbo_stew.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["hackers"] = { name = "hackers", label = "Hackers", weight = 8, type = "item", image = "hackers.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["health_bar"] = { name = "health_bar", label = "Health Bar", weight = 8, type = "item", image = "health_bar.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["heartysandwich"] = { name = "heartysandwich", label = "Hearty Sandwich", weight = 8, type = "item", image = "heartysandwich.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["honey"] = { name = "honey", label = "Honey", weight = 8, type = "item", image = "honey.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["hot_wings"] = { name = "hot_wings", label = "Hot Wings", weight = 8, type = "item", image = "hot_wings.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["hotdog"] = { name = "hotdog", label = "Hotdog", weight = 8, type = "item", image = "hotdog.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["ice_cream"] = { name = "ice_cream", label = "Ice Cream", weight = 8, type = "item", image = "ice_cream.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["jail_breakers"] = { name = "jail_breakers", label = "Jail Breakers", weight = 8, type = "item", image = "jail_breakers.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["mango_pot"] = { name = "mango_pot", label = "Mango Pot", weight = 8, type = "item", image = "mango_pot.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["meat_stew"] = { name = "meat_stew", label = "Meat Stew", weight = 8, type = "item", image = "meat_stew.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["meow_chow"] = { name = "meow_chow", label = "Meow Chow", weight = 8, type = "item", image = "meow_chow.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["mexican"] = { name = "mexican", label = "Mexican", weight = 8, type = "item", image = "mexican.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["mushroom"] = { name = "mushroom", label = "Mushroom", weight = 8, type = "item", image = "mushroom.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["natures_call"] = { name = "natures_call", label = "Natures Call", weight = 8, type = "item", image = "natures_call.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["nerd_tats"] = { name = "nerd_tats", label = "Nerd Tats", weight = 8, type = "item", image = "nerd_tats.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["nuggets"] = { name = "nuggets", label = "Nuggets", weight = 8, type = "item", image = "nuggets.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["oh_shitz_drops"] = { name = "oh_shitz_drops", label = "Oh Shitz Drops", weight = 8, type = "item", image = "oh_shitz_drops.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["potato_mouldy"] = { name = "potato_mouldy", label = "Potato Mouldy", weight = 8, type = "item", image = "potato_mouldy.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pumpkin_bread"] = { name = "pumpkin_bread", label = "Pumpkin Bread", weight = 8, type = "item", image = "pumpkin_bread.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pumpkin_cheesecake"] = { name = "pumpkin_cheesecake", label = "Pumpkin Cheesecake", weight = 8, type = "item", image = "pumpkin_cheesecake.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pumpkinpie_slice"] = { name = "pumpkinpie_slice", label = "Pumpkin Pie Slice", weight = 8, type = "item", image = "pumpkinpie_slice.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["purrito"] = { name = "purrito", label = "Purrito", weight = 8, type = "item", image = "purrito.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rabbitfood"] = { name = "rabbitfood", label = "Rabbit Food", weight = 8, type = "item", image = "rabbitfood.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Rations
    ["ration_beef"] = { name = "ration_beef", label = "Beef Rations", weight = 8, type = "item", image = "ration_beef.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["ration_chicken"] = { name = "ration_chicken", label = "Chicken Rations", weight = 8, type = "item", image = "ration_chicken.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["ration_lamb"] = { name = "ration_lamb", label = "Lamb Rations", weight = 8, type = "item", image = "ration_lamb.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- More Food Items
    ["ravioli"] = { name = "ravioli", label = "Ravioli", weight = 8, type = "item", image = "ravioli.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rice"] = { name = "rice", label = "Rice", weight = 8, type = "item", image = "rice.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rock_busters"] = { name = "rock_busters", label = "Rock Busters", weight = 8, type = "item", image = "rock_busters.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rotting_meat"] = { name = "rotting_meat", label = "Rotting Meat", weight = 8, type = "item", image = "rotting_meat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sham"] = { name = "sham", label = "Sham", weight = 8, type = "item", image = "sham.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sham_chowder"] = { name = "sham_chowder", label = "Sham Chowder", weight = 8, type = "item", image = "sham_chowder.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sham_sandwich"] = { name = "sham_sandwich", label = "Sham Sandwich", weight = 8, type = "item", image = "sham_sandwich.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["shephards_pie"] = { name = "shephards_pie", label = "Shephards Pie", weight = 8, type = "item", image = "shephards_pie.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["shushi"] = { name = "shushi", label = "Shushi", weight = 8, type = "item", image = "shushi.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sirloin_burger"] = { name = "sirloin_burger", label = "Sirloin Burger", weight = 8, type = "item", image = "sirloin_burger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["skull_crushers"] = { name = "skull_crushers", label = "Skull Crushers", weight = 8, type = "item", image = "skull_crushers.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sloppy_joe"] = { name = "sloppy_joe", label = "Sloppy Joe", weight = 8, type = "item", image = "sloppy_joe.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["soup_miso"] = { name = "soup_miso", label = "Soup Miso", weight = 8, type = "item", image = "soup_miso.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["spaghetti"] = { name = "spaghetti", label = "Spaghetti", weight = 8, type = "item", image = "spaghetti.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["spicy_chicken_wrap"] = { name = "spicy_chicken_wrap", label = "Spicy Chicken Wrap", weight = 8, type = "item", image = "spicy_chicken_wrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["stash_chilli"] = { name = "stash_chilli", label = "Stash Chilli", weight = 8, type = "item", image = "stash_chilli.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["steak_potato"] = { name = "steak_potato", label = "Steak Potato", weight = 8, type = "item", image = "steak_potato.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["stew_vegetable"] = { name = "stew_vegetable", label = "Stew Vegetable", weight = 8, type = "item", image = "stew_vegetable.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sugar_butts"] = { name = "sugar_butts", label = "Sugar Butts", weight = 8, type = "item", image = "sugar_butts.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tortia"] = { name = "tortia", label = "Tortia", weight = 8, type = "item", image = "tortia.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tosti"] = { name = "tosti", label = "Tosti", weight = 8, type = "item", image = "tosti.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tune_toast"] = { name = "tune_toast", label = "Tune Toast", weight = 8, type = "item", image = "tune_toast.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["yucca_fruit"] = { name = "yucca_fruit", label = "Yucca Fruit", weight = 8, type = "item", image = "yucca_fruit.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Pasta and Italian Dishes
    ["alfredomontamore"] = { name = "alfredomontamore", label = "Alfredo Montamore", weight = 8, type = "item", image = "alfredomontamore.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["alla"] = { name = "alla", label = "Alla", weight = 8, type = "item", image = "alla.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bbqporkmac"] = { name = "bbqporkmac", label = "BBQ Pork Mac", weight = 8, type = "item", image = "bbqporkmac.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bbq-pulled-pork"] = { name = "bbq-pulled-pork", label = "BBQ Pulled Pork", weight = 8, type = "item", image = "bbq-pulled-pork.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["beef_chilli"] = { name = "beef_chilli", label = "Beef Chilli", weight = 8, type = "item", image = "beef_chilli.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["beefstroganoff"] = { name = "beefstroganoff", label = "Beef Stroganoff", weight = 8, type = "item", image = "beefstroganoff.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bolognese"] = { name = "bolognese", label = "Bolognese", weight = 8, type = "item", image = "bolognese.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bolognese2"] = { name = "bolognese2", label = "Bolognese 2", weight = 8, type = "item", image = "bolognese2.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bplate"] = { name = "bplate", label = "B Plate", weight = 8, type = "item", image = "bplate.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["buffalochickenmac"] = { name = "buffalochickenmac", label = "Buffalo Chicken Mac", weight = 8, type = "item", image = "buffalochickenmac.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["butterednoodles"] = { name = "butterednoodles", label = "Buttered Noodles", weight = 8, type = "item", image = "butterednoodles.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["calamari"] = { name = "calamari", label = "Calamari", weight = 8, type = "item", image = "calamari.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cplate"] = { name = "cplate", label = "C Plate", weight = 8, type = "item", image = "cplate.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["eggsbacon"] = { name = "eggsbacon", label = "Eggs Bacon", weight = 8, type = "item", image = "eggsbacon.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["frenchtoast"] = { name = "frenchtoast", label = "French Toast", weight = 8, type = "item", image = "frenchtoast.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["friedpick"] = { name = "friedpick", label = "Fried Pickle", weight = 8, type = "item", image = "friedpick.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["fries"] = { name = "fries", label = "Fries", weight = 8, type = "item", image = "fries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["japanesepannoodles"] = { name = "japanesepannoodles", label = "Japanese Pan Noodles", weight = 8, type = "item", image = "japanesepannoodles.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["lasagna"] = { name = "lasagna", label = "Lasagna", weight = 8, type = "item", image = "lasagna.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["mac_and_cheese"] = { name = "mac_and_cheese", label = "Mac and Cheese", weight = 8, type = "item", image = "mac_and_cheese.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["maccheese"] = { name = "maccheese", label = "Mac Cheese", weight = 8, type = "item", image = "maccheese.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["meatball"] = { name = "meatball", label = "Meatball", weight = 8, type = "item", image = "meatball.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["medfruits"] = { name = "medfruits", label = "Med Fruits", weight = 8, type = "item", image = "medfruits.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["meetballs"] = { name = "meetballs", label = "Meetballs", weight = 8, type = "item", image = "meetballs.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["miso"] = { name = "miso", label = "Miso", weight = 8, type = "item", image = "miso.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["noodlebowl"] = { name = "noodlebowl", label = "Noodle Bowl", weight = 8, type = "item", image = "noodlebowl.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["nplate"] = { name = "nplate", label = "N Plate", weight = 8, type = "item", image = "nplate.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["padthai"] = { name = "padthai", label = "Pad Thai", weight = 8, type = "item", image = "padthai.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pasta"] = { name = "pasta", label = "Pasta", weight = 8, type = "item", image = "pasta.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pastafresca"] = { name = "pastafresca", label = "Pasta Fresca", weight = 8, type = "item", image = "pastafresca.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pennerosa"] = { name = "pennerosa", label = "Pennerosa", weight = 8, type = "item", image = "pennerosa.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pescatore"] = { name = "pescatore", label = "Pescatore", weight = 8, type = "item", image = "pescatore.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pestocavatappi"] = { name = "pestocavatappi", label = "Pesto Cavatappi", weight = 8, type = "item", image = "pestocavatappi.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["ramen"] = { name = "ramen", label = "Ramen", weight = 8, type = "item", image = "ramen.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rib-steak"] = { name = "rib-steak", label = "Rib Steak", weight = 8, type = "item", image = "rib-steak.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["rplate"] = { name = "rplate", label = "R Plate", weight = 8, type = "item", image = "rplate.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sirloinsteak"] = { name = "sirloinsteak", label = "Sirloin Steak", weight = 8, type = "item", image = "sirloinsteak.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["spaghettimeatballs"] = { name = "spaghettimeatballs", label = "Spaghetti Meatballs", weight = 8, type = "item", image = "spaghettimeatballs.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["spicychipotleadobopork"] = { name = "spicychipotleadobopork", label = "Spicy Chipotle Adobo Pork", weight = 8, type = "item", image = "spicychipotleadobopork.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["spicykoreanbeefnoodles"] = { name = "spicykoreanbeefnoodles", label = "Spicy Korean Beef Noodles", weight = 8, type = "item", image = "spicykoreanbeefnoodles.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["splate"] = { name = "splate", label = "S Plate", weight = 8, type = "item", image = "splate.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["thaigreencurry"] = { name = "thaigreencurry", label = "Thai Green Curry", weight = 8, type = "item", image = "thaigreencurry.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["wings"] = { name = "wings", label = "Wings", weight = 8, type = "item", image = "wings.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["wisconsinmacandcheese"] = { name = "wisconsinmacandcheese", label = "Wisconsin Mac and Cheese", weight = 8, type = "item", image = "wisconsinmacandcheese.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["zucchinitrufflemac"] = { name = "zucchinitrufflemac", label = "Zucchini Truffle Mac", weight = 8, type = "item", image = "zucchinitrufflemac.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Burgers
    ["bacon_cheeseburger"] = { name = "bacon_cheeseburger", label = "Bacon Cheeseburger", weight = 8, type = "item", image = "bacon_cheeseburger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-bleeder"] = { name = "burger-bleeder", label = "Burger Bleeder", weight = 8, type = "item", image = "burger-bleeder.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-chickenwrap"] = { name = "burger-chickenwrap", label = "Burger Chickenwrap", weight = 8, type = "item", image = "burger-chickenwrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-creampie"] = { name = "burger-creampie", label = "Burger Creampie", weight = 8, type = "item", image = "burger-creampie.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-fries"] = { name = "burger-fries", label = "Burger Fries", weight = 8, type = "item", image = "burger-fries.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-goatwrap"] = { name = "burger-goatwrap", label = "Burger Goatwrap", weight = 8, type = "item", image = "burger-goatwrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-heartstopper"] = { name = "burger-heartstopper", label = "Burger Heartstopper", weight = 8, type = "item", image = "burger-heartstopper.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-meatfree"] = { name = "burger-meatfree", label = "Burger Meatfree", weight = 8, type = "item", image = "burger-meatfree.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-moneyshot"] = { name = "burger-moneyshot", label = "Burger Moneyshot", weight = 8, type = "item", image = "burger-moneyshot.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-rimjob"] = { name = "burger-rimjob", label = "Burger Rimjob", weight = 8, type = "item", image = "burger-rimjob.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-shotnuggets"] = { name = "burger-shotnuggets", label = "Burger Shotnuggets", weight = 8, type = "item", image = "burger-shotnuggets.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-shotrings"] = { name = "burger-shotrings", label = "Burger Shotrings", weight = 8, type = "item", image = "burger-shotrings.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["burger-torpedo"] = { name = "burger-torpedo", label = "Burger Torpedo", weight = 8, type = "item", image = "burger-torpedo.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["golden_rings"] = { name = "golden_rings", label = "Golden Rings", weight = 8, type = "item", image = "golden_rings.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["hamburger"] = { name = "hamburger", label = "Hamburger", weight = 8, type = "item", image = "hamburger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Salads
    ["salad1"] = { name = "salad1", label = "Salad 1", weight = 8, type = "item", image = "salad1.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["salad2"] = { name = "salad2", label = "Salad 2", weight = 8, type = "item", image = "salad2.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["salad3"] = { name = "salad3", label = "Salad 3", weight = 8, type = "item", image = "salad3.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Seafood
    ["grilltunak"] = { name = "grilltunak", label = "Grill Tunak", weight = 8, type = "item", image = "grilltunak.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["fishburger"] = { name = "fishburger", label = "Fishburger", weight = 8, type = "item", image = "fishburger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["grillchobotnice"] = { name = "grillchobotnice", label = "Grill Chobotnice", weight = 8, type = "item", image = "grillchobotnice.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["grilllosos"] = { name = "grilllosos", label = "Grill Losos", weight = 8, type = "item", image = "grilllosos.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["kalamary"] = { name = "kalamary", label = "Kalamary", weight = 8, type = "item", image = "kalamary.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["krevetagrilll"] = { name = "krevetagrilll", label = "Kreveta Grilll", weight = 8, type = "item", image = "krevetagrilll.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["krevetasalat"] = { name = "krevetasalat", label = "Kreveta Salat", weight = 8, type = "item", image = "krevetasalat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["krevetovywrap"] = { name = "krevetovywrap", label = "Krevetovy Wrap", weight = 8, type = "item", image = "krevetovywrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["krevety"] = { name = "krevety", label = "Krevety", weight = 8, type = "item", image = "krevety.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["lososburger"] = { name = "lososburger", label = "Losos Burger", weight = 8, type = "item", image = "lososburger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["lososwrap"] = { name = "lososwrap", label = "Losos Wrap", weight = 8, type = "item", image = "lososwrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tunakburger"] = { name = "tunakburger", label = "Tunak Burger", weight = 8, type = "item", image = "tunakburger.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["tunakwrap"] = { name = "tunakwrap", label = "Tunak Wrap", weight = 8, type = "item", image = "tunakwrap.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    
    -- Bakery and Desserts
    ["almond_croissant"] = { name = "almond_croissant", label = "Almond Croissant", weight = 8, type = "item", image = "almond_croissant.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["bagel"] = { name = "bagel", label = "Bagel", weight = 8, type = "item", image = "bagel.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["butter_croissant"] = { name = "butter_croissant", label = "Butter Croissant", weight = 8, type = "item", image = "butter_croissant.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cake"] = { name = "cake", label = "Cake", weight = 8, type = "item", image = "cake.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cannoli"] = { name = "cannoli", label = "Cannoli", weight = 8, type = "item", image = "cannoli.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cherry_crown_pastry"] = { name = "cherry_crown_pastry", label = "Cherry Crown Pastry", weight = 8, type = "item", image = "cherry_crown_pastry.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["chocolate_twista"] = { name = "chocolate_twista", label = "Chocolate Twista", weight = 8, type = "item", image = "chocolate_twista.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["croissant"] = { name = "croissant", label = "Croissant", weight = 8, type = "item", image = "croissant.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cupcake"] = { name = "cupcake", label = "Cupcake", weight = 8, type = "item", image = "cupcake.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["cupcake2"] = { name = "cupcake2", label = "Cupcake 2", weight = 8, type = "item", image = "cupcake2.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["muffin"] = { name = "muffin", label = "Muffin", weight = 8, type = "item", image = "muffin.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["pain_au_chocolat"] = { name = "pain_au_chocolat", label = "Pain au Chocolat", weight = 8, type = "item", image = "pain_au_chocolat.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["sausageroll"] = { name = "sausageroll", label = "Sausage Roll", weight = 8, type = "item", image = "sausageroll.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["wedding_cake"] = { name = "wedding_cake", label = "Wedding Cake", weight = 8, type = "item", image = "wedding_cake.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },
    ["weddingcake"] = { name = "weddingcake", label = "Weddingcake", weight = 8, type = "item", image = "weddingcake.png", unique = false, useable = true, shouldClose = true, combinable = nil, description = "" },

}
